<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="fixed_parts" >

  <xacro:macro name="fixed_parts"
   params="origin_frame:=${'world'} ">

    <xacro:property name="stl_frame_X" value="0.56"/>
    <xacro:property name="table_X" value="0.95"/>
    <xacro:property name="table_Y" value="1.18"/>
    <xacro:property name="table_Z" value="0.9165"/>
    <xacro:property name="mesh_file" value="file://$(find ur_description)/meshes/table/table_simplified.stl"/>

    <link name="tabletop">
      <inertial>
          <mass value="1000.0" />
          <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
      </inertial>
      <collision>
        <origin  xyz="${0.5*table_X} ${0.5*table_Y} ${-0.5*table_Z}" rpy="0 0 1.570796327" />
        <geometry>
          <box size="${table_Y} ${table_X} ${table_Z}"/>
        </geometry>
        <material
          name="">
          <color
            rgba="0.6 0.6 0.6 1" />
        </material>
      </collision>
      <visual>
        <origin  xyz="${stl_frame_X} 0.0 ${-table_Z}" rpy="0 0 1.570796327" />
        <geometry>
          <mesh 
            filename="${mesh_file}" scale="0.001 0.001 0.001"/>
        </geometry>
          <material
          name="">
          <color
            rgba="0.5 0.5 0.5 1" />
        </material>
      </visual>
    </link>
    <joint name="world_to_tabletop" type="fixed">
      <parent link = "${origin_frame}" />
      <child  link = "tabletop" />
      <origin xyz="0.0 0.0 ${table_Z}" rpy="0 0 0" />
    </joint>

  </xacro:macro>
</robot>


